import {defineField, defineType} from 'sanity'

export const project = defineType({
  name: 'project',
  title: 'Case Study',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'type', title: 'Project type', type: 'string'}),
    defineField({name: 'company', title: 'Company', type: 'string'}),
    defineField({name: 'institution', title: 'Institution', type: 'string'}),
    defineField({name: 'period', title: 'Period', type: 'string'}),
    defineField({name: 'cardSubtext', title: 'Card subtext', type: 'string'}),
    defineField({name: 'description', title: 'Description', type: 'text'}),
    defineField({name: 'url', title: 'External URL', type: 'url'}),
    defineField({name: 'role', title: 'Role', type: 'string'}),
    defineField({name: 'team', title: 'Team', type: 'string'}),
    defineField({
      name: 'tools',
      title: 'Tools',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({name: 'problem', title: 'Problem', type: 'text'}),
    defineField({name: 'targetAudience', title: 'Target audience', type: 'text'}),
    defineField({name: 'research', title: 'Research', type: 'text'}),
    defineField({name: 'hmw', title: 'How might we', type: 'text'}),
    defineField({name: 'approach', title: 'Approach', type: 'text'}),
    defineField({name: 'prototype', title: 'Prototype notes', type: 'text'}),
    defineField({name: 'prototypeFrame', title: 'Prototype embed URL', type: 'url'}),
    defineField({name: 'takeStepBack', title: 'Take a step back', type: 'text'}),
    defineField({name: 'painPointsIntro', title: 'Pain points intro', type: 'text'}),
    defineField({name: 'impactOverview', title: 'Impact overview', type: 'text'}),
    defineField({
      name: 'learnings',
      title: 'Learnings',
      type: 'array',
      of: [{type: 'text'}],
    }),
    defineField({
      name: 'keyFeatures',
      title: 'Key features',
      type: 'array',
      of: [{type: 'text'}],
    }),
    defineField({
      name: 'results',
      title: 'Results',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'impact',
      title: 'Impact',
      type: 'array',
      of: [{type: 'text'}],
    }),
    defineField({
      name: 'businessOpportunity',
      title: 'Business opportunity',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'details',
      title: 'Details (bullet list)',
      type: 'array',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'detailSections',
      title: 'Detail sections',
      type: 'array',
      of: [{type: 'detailSection'}],
    }),
    defineField({
      name: 'designGallery',
      title: 'Design gallery',
      type: 'array',
      of: [{type: 'galleryItem'}],
    }),
    defineField({
      name: 'explorations',
      title: 'Explorations',
      type: 'array',
      of: [{type: 'exploration'}],
    }),
    defineField({
      name: 'painPoints',
      title: 'Pain points',
      type: 'array',
      of: [{type: 'painPoint'}],
    }),
    defineField({name: 'problemImage', title: 'Problem image', type: 'imageBlock'}),
    defineField({name: 'targetAudienceImage', title: 'Target audience image', type: 'imageBlock'}),
    defineField({name: 'keyFeatureImage', title: 'Key feature image', type: 'imageBlock'}),
    defineField({
      name: 'order',
      title: 'Sort order',
      type: 'number',
      description: 'Lower numbers appear first on the Work page',
    }),
    defineField({
      name: 'hidden',
      title: 'Hide from Work page',
      type: 'boolean',
      initialValue: false,
    }),
  ],
  preview: {
    select: {title: 'title', subtitle: 'company', media: 'cardSubtext'},
  },
})
