export const projectsQuery = `*[_type == "project" && !hidden] | order(order asc, title asc) {
  title,
  "slug": slug.current,
  type,
  company,
  institution,
  period,
  cardSubtext,
  description,
  url,
  role,
  team,
  tools,
  problem,
  targetAudience,
  research,
  hmw,
  approach,
  prototype,
  prototypeFrame,
  takeStepBack,
  painPointsIntro,
  impactOverview,
  learnings,
  keyFeatures,
  results,
  impact,
  businessOpportunity,
  details,
  detailSections,
  designGallery,
  explorations,
  painPoints,
  problemImage,
  targetAudienceImage,
  keyFeatureImage
}`

export const projectBySlugQuery = `*[_type == "project" && slug.current == $slug][0] {
  title,
  "slug": slug.current,
  type,
  company,
  institution,
  period,
  cardSubtext,
  description,
  url,
  role,
  team,
  tools,
  problem,
  targetAudience,
  research,
  hmw,
  approach,
  prototype,
  prototypeFrame,
  takeStepBack,
  painPointsIntro,
  impactOverview,
  learnings,
  keyFeatures,
  results,
  impact,
  businessOpportunity,
  details,
  detailSections,
  designGallery,
  explorations,
  painPoints,
  problemImage,
  targetAudienceImage,
  keyFeatureImage
}`

export const siteSettingsQuery = `*[_type == "siteSettings"][0] {
  name,
  email,
  website,
  linkedin,
  phone,
  github,
  experienceIntro,
  awards,
  certifications
}`

export const experienceQuery = `*[_type == "experience"] | order(order asc, company asc) {
  role,
  company,
  period,
  achievements
}`
